from yacs.config import CfgNode as CN

_C = CN()

_C.DATASET = CN()
_C.DATASET.TRAIN = CN()
_C.DATASET.TRAIN.SOURCE_NAME = None
_C.DATASET.TRAIN.SOURCE_PATH = None
_C.DATASET.TRAIN.TARGET_NAME = None
_C.DATASET.TRAIN.TARGET_PATH = None
_C.DATASET.FINETUNE = CN()
_C.DATASET.FINETUNE.SOURCE_NAME = None
_C.DATASET.FINETUNE.SOURCE_PATH = None
_C.DATASET.FINETUNE.TARGET_NAME = None
_C.DATASET.FINETUNE.TARGET_PATH = None
_C.DATASET.NORMALIZE = True

_C.MODEL = CN()
_C.MODEL.NAME = None
_C.MODEL.CHECKPOINT = None
_C.MODEL.CHANNELS = None
_C.MODEL.DIM = None

_C.TRAIN = CN()
_C.TRAIN.SAVE = None
_C.TRAIN.LOG = None
_C.TRAIN.LOG_INTERVAL = None
_C.TRAIN.HYPER = CN()
_C.TRAIN.HYPER.EPOCHS = None
_C.TRAIN.HYPER.BATCH_SIZE = None
_C.TRAIN.HYPER.LEARNING_RATE = None

_C.INFERENCE = CN()
_C.INFERENCE.SAVE = None
_C.INFERENCE.SOURCE = None
_C.INFERENCE.TARGET = None

cfg = _C